{% set name = "omegaconf" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b945422a8cece6da2b193ff5b64b30f7ebc6510819ac15b31d5d28173883d999

build:
  number: 0
  skip: true  # [py2k and py==34 and py==35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - pyyaml
    - dataclasses  # [py==36]
    - typing_extensions

test:
  imports:
    - omegaconf
  requires:
    - pytest
    - pytest-mock
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/omry/omegaconf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Flexible python configuration system

  description: |
    OmegaConf is a hierarchical configuration system, with support for merging
    configurations from multiple sources (YAML config files,
    dataclasses/objects and CLI arguments) providing a consistent API
    regardless of how the configuration was created.
  doc_url: https://omegaconf.readthedocs.io/
  dev_url: https://github.com/omry/omegaconf

extra:
  recipe-maintainers:
    - mdraw
    - omry
