{% set name = "omegaconf" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5d4b6d29955cc50ad50c46dc269bcd92c6e00f5f90d23ab5fee7bfca4ba4cc7

build:
  number: 0
  # skip s390x because openjdk is not available
  skip: true  # [s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    #
    # antlr is included as binary in build_helpers/bin/antlr-4.9.3-complete.jar
    # also for this reason and the next point, we need the java sdk
    # https://github.com/omry/omegaconf/blob/fd73050/build_helpers/build_helpers.py#L33
    # in future versions it will be included in the vendor folder, see open PR: https://github.com/omry/omegaconf/pull/1114
    # 
    # - antlr 4.9
    #
    # in setup.py there is an ANTLRCommand import
    # https://github.com/omry/omegaconf/blob/350bdb632865c5dd2286f2f6521acefe4abd843d/setup.py#L16-L23
    # which is a command run using java, therefore java jdk is needed
    # https://github.com/omry/omegaconf/blob/fd73050/build_helpers/build_helpers.py#L30-L40
    - openjdk
  run:
    - python
    - pyyaml >=5.1.0
    - antlr4-python3-runtime 4.9
    - typing_extensions

test:
  imports:
    - omegaconf
  requires:
    - pytest
    - pytest-benchmark
    - pytest-mock
    - pytest-lazy-fixture
    - pip
    # There is an `import attr` in https://github.com/omry/omegaconf/blob/350bdb6/tests/__init__.py#L6 
    # satisfied by `attrs`, added in a later commit in `main`: https://github.com/omry/omegaconf/commit/a0cc301
    - attrs
    # Temporary pin <https://github.com/conda-forge/omegaconf-feedstock/pull/40#issuecomment-1294669062>
  source_files:
    - tests
  commands:
    - pip check
    - pytest --ignore tests/test_pydev_resolver_plugin.py

about:
  home: https://github.com/omry/omegaconf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Flexible python configuration system
  description: |
    OmegaConf is a hierarchical configuration system, with support for merging
    configurations from multiple sources (YAML config files,
    dataclasses/objects and CLI arguments) providing a consistent API
    regardless of how the configuration was created.
  doc_url: https://omegaconf.readthedocs.io/
  dev_url: https://github.com/omry/omegaconf

extra:
  recipe-maintainers:
    - maresb
    - mdraw
    - omry
    - benjaminrwilson
